

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway_generic?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123qweasd
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: log

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20081
    name: dubbo
  application:
    name: api-generic-consumer
    qos-port: 3333
  provider:
    version: 1.0.0
  scan:
    basePackages: com.example.gateway.facade.impl
  consumer:
    version: 1.0.0

logging:
  config: classpath:logback-test.xml
server:
  port: 8082
